AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  assignment-student-grading

  Sample SAM Template for assignment-student-grading

Globals:
  Function:
    Timeout: 20
    Runtime: java11
    Architectures:
      - x86_64
    MemorySize: 512

Resources:

  StudentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}

  StudentsUpdateMonitoringFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: StudentsGrading/update-monitoring/target/update-monitoring-1.0.jar
      Handler: net.shyshkin.study.aws.serverless.s3sns.assignment.StudentUpdateMonitoring::handleRequest
      Layers:
        - !Ref S3SQSLambdaLayer
        - !Ref LoggingLambdaLayer
        - !Ref LambdaCoreLambdaLayer
        - !Ref MappingLambdaLayer
      Environment:
        Variables:
          STUDENTS_GRADE_QUEUE_URL: !Ref StudentsGradeQueue
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}
        - SQSSendMessagePolicy:
            QueueName: !GetAtt StudentsGradeQueue.QueueName
      Events:
        S3StudentsUpdateEvent:
          Type: S3
          Properties:
            Bucket: !Ref StudentsBucket
            Events: s3:ObjectCreated:*
      DeadLetterQueue:
        Type: SNS
        TargetArn: !Ref StudentsGradeDLQ
      EventInvokeConfig:
        MaximumRetryAttempts: 0

  StudentsGradeQueue:
    Type: AWS::SQS::Queue

  StudentsGradeDLQ:
    Type: AWS::SNS::Topic

  StudentsGradeLoggingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: StudentsGrading/grade-logging/target/grade-logging-1.0.jar
      Handler: net.shyshkin.study.aws.serverless.s3sns.assignment.StudentGradeLogging::handleRequest
      Layers:
        - !Ref LoggingLambdaLayer
        - !Ref LambdaCoreLambdaLayer
        - !Ref MappingLambdaLayer
      Events:
        SQSStudentsGradeEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt StudentsGradeQueue.Arn
            BatchSize: 10

  ErrorHandlingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: StudentsGrading/error-handling/target/error-handling-1.0.jar
      Handler: net.shyshkin.study.aws.serverless.s3sns.assignment.ErrorHandler::handleRequest
      Layers:
        - !Ref LoggingLambdaLayer
        - !Ref LambdaCoreLambdaLayer
      Events:
        DLQEvent:
          Type: SNS
          Properties:
            Topic: !Ref StudentsGradeDLQ

  S3SQSLambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: StudentsGrading/layers/s3sqs-lambda-layer/target/s3sqs-lambda-layer.zip
      CompatibleRuntimes:
        - java11

  LoggingLambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: StudentsGrading/layers/logging-lambda-layer/target/logging-lambda-layer.zip
      CompatibleRuntimes:
        - java11

  LambdaCoreLambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: StudentsGrading/layers/lambda-core-lambda-layer/target/lambda-core-lambda-layer.zip
      CompatibleRuntimes:
        - java11

  MappingLambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: StudentsGrading/layers/mapping-lambda-layer/target/mapping-lambda-layer.zip
      CompatibleRuntimes:
        - java11


