AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  orders-api

  Sample SAM Template for orders-api

Globals:
  Function:
    CodeUri: OrdersApi
    Runtime: java11
    MemorySize: 256
    Timeout: 40
    Environment:
      Variables:
        ORDERS_TABLE: !Ref OrdersTable

Resources:
  CreateOrderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: net.shyshkin.study.aws.serverless.api.CreateOrderFunction::handleRequest
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdersTable
      Events:
        CreateOrderEvent:
          Type: Api
          Properties:
            Method: POST
            Path: /orders

  ReadOrdersFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: net.shyshkin.study.aws.serverless.api.ReadOrdersFunction::handleRequest
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref OrdersTable
      Events:
        CreateOrderEvent:
          Type: Api
          Properties:
            Method: GET
            Path: /orders

  OrdersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: Number

Outputs:
  OrdersApi:
    Description: "API Gateway endpoint URL for Prod stage for create and get orders endpoints"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/orders"





