AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  orders-api

  Sample SAM Template for orders-api

Globals:
  Function:
    CodeUri: OrdersApi
    Runtime: java11
    MemorySize: 128
    Timeout: 20

Resources:
  CreateOrderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: net.shyshkin.study.aws.serverless.api.CreateOrderFunction::handleRequest
      Events:
        CreateOrderEvent:
          Type: Api
          Properties:
            Method: POST
            Path: /orders

  ReadOrdersFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: net.shyshkin.study.aws.serverless.api.ReadOrdersFunction::handleRequest
      Events:
        CreateOrderEvent:
          Type: Api
          Properties:
            Method: GET
            Path: /orders






