AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  patient-checkout

  Sample SAM Template for patient-checkout

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  PatientCheckoutLambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: PatientCheckout
      Handler: net.shyshkin.study.aws.serverless.s3sns.PatientCheckoutLambda::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        PatientCheckout:
          Type: S3
          Properties:
            Bucket: !Ref PatientCheckoutS3Bucket
            Events: s3:ObjectCreated:*
      Policies:
        - S3ReadPolicy:
            BucketName:  !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}

  PatientCheckoutS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}

