openapi: "3.0.1"
info:
  title: "Orders API"
  description: "Orders API for Gateway-DynamoDB SAM Tutorial"
  version: "2021-12-12T20:20:06Z"
servers:
- url: "https://ubqqu9m585.execute-api.eu-north-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "/Prod"
paths:
  /orders:
    get:
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReadOrdersResponse"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: OrdersAPIGatewayRole.Arn
        httpMethod: "POST"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:dynamodb:action/Scan"
        responses:
          default:
            statusCode: "200"
            responseTemplates:
              application/json: "#set($inputRoot = $input.path('$'))\r\n[\r\n    #foreach($elem\
                \ in $inputRoot.Items) {\r\n        \"id\": $elem.id.N,\r\n      \
                \  \"itemName\": \"$elem.itemName.S\",\r\n        \"quantity\": $elem.quantity.N\r\
                \n    }#if($foreach.hasNext),#end\r\n    #end\r\n]\r\n"
        requestTemplates:
          application/json:
            Fn::Sub: "{\r\n  \"TableName\": \"${OrdersTable}\"\r\n}"
        passthroughBehavior: "when_no_templates"
        type: "aws"

    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
        required: true
      responses:
        "201":
          description: "Order Created Successfully"
          content: {}
      x-amazon-apigateway-request-validator: "Validate body"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: OrdersAPIGatewayRole.Arn
        httpMethod: "POST"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:dynamodb:action/PutItem"
        responses:
          default:
            statusCode: "201"
        requestTemplates:
          application/json: "{ \r\n    \"TableName\": \"orders-simple-api-stack-OrdersTable-XPBYDXPGD1KM\"\
            ,\r\n    \"Item\": {\r\n        \"id\": {\r\n            \"N\": \"$input.path('$.id')\"\
            \r\n        },\r\n        \"itemName\": {\r\n            \"S\": \"$input.path('$.itemName')\"\
            \r\n        },\r\n        \"quantity\": {\r\n            \"N\": \"$input.path('$.quantity')\"\
            \r\n        }\r\n    }\r\n}"
        passthroughBehavior: "when_no_templates"
        type: "aws"
components:
  schemas:
    Order:
      required:
        - "id"
        - "itemName"
        - "quantity"
      type: "object"
      properties:
        id:
          type: "number"
        itemName:
          type: "string"
        quantity:
          type: "number"
    ReadOrdersResponse:
      type: "array"
      items:
        $ref: '#/components/schemas/Order'
x-amazon-apigateway-request-validators:
  Validate body:
    validateRequestParameters: false
    validateRequestBody: true
