AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  customers-api

  Sample SAM Template for customers-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    Runtime: java11
    Architectures:
      - x86_64
    MemorySize: 256
    Environment:
      Variables:
        PARAM1: VALUE

Resources:
  CreateCustomerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: CustomersApi
      Handler: net.shyshkin.study.aws.serverless.api.CreateCustomerFunction::handleRequest
      Events:
        CreateNewCustomer:
          Type: Api
          Properties:
            Path: /customers
            Method: post

Outputs:
  CustomersApi:
    Description: "API Gateway endpoint URL for Prod stage for Customers API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/customers"

