### Locally - sam local start-api
POST http://localhost:3000/orders
Content-Type: application/json

{
  "id": 1234,
  "itemName": "milk",
  "quantity": 4321
}

### Remotely - sam deploy
POST https://le91t4b8th.execute-api.eu-north-1.amazonaws.com/Prod/orders
Content-Type: application/json

{
  "id": {{$randomInt}},
  "itemName": "milk",
  "quantity": {{$randomInt}}
}


